step-runner-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:r6ASu1Lbn5/qWCTh55f97DF7Gqt1pVPeXtEUZKt31CsH2MnmZmveeN8/gm4hXKsM+I42c6sw2Yq6bYA/WQVyT30eS7cblVjSVVvMKXasjHdzyYe8YZ4WMJQ3Q35r1l8s1kqWp+y6710GtEkI+M6gAR0StseVKR/6pmJtV2lfmJuohf2Y9cxyHIuvzsjF7TiNySmajOAcIEDLgii+RCAYV9G6BW/eV4eD5eXRUeqgcG0vaNkNlc7GzH2afndzzLEDMX2nVt1z3QjaNMPeO2WQPd6+FBSKOOEEZxMK+7dB1qdEUTLNpYgJ5G5iiFchCIJMYndjBCIGGX49vHAqnLJYXUuurWltLCByuVPFm4ycZ5xlRSZa7dgEsIL42D2O+drZVnPF7VT6AzptrLr/A2PdOc1PHdBG5ZL4Ixs9jmhcti6gK6t2iBkpuTAvob+U7pQi0DGqu7q/7DKQfou576EhUfi7Ewp7DtA4Un9MkEpCFFBVSrqMqu+TQWf25kh+JPsspMNigEMwFIr0QrcQg+wzWA2K0Mnt5h1v4wqGeC79vDtS/BHFoP6hwFTMJ9U/ClU/+bR+SjNnSzZtcHF2Kpw4+FYVa0h8H2a0IRNYOYatXd9ixNA4X7GncdkgZ/KjVSshF33FbO8NE6iemKDIoigybKOcdOdXhnZCM1QRMwurtcoEKiK+CPbnQRbgd57PnIY5/AsabbUDueVG1t/QJpCJu1Wg/4O/HJG5c1RAiWVhnYZ1fldPtMCGBDNUip3wHdUyNQo0nofhYKNRjX1JXAhz96J6pRkxXnhsy6t0S/Li713fLZr81Yy2psE3Gb49iS65d07vLjEDFkc+KWePwhGfAyomtzBfTU2IpqmmnVUnDys97TJbMiJgX3C+raiP649KzYsqPExMH5iUAbOkeXDCgj093fI14VfyEzmluRiM3pcPy2EqFSz8cy+bva5pzMVhr8nV+AkPwx4eilW0RSr46k28saZCfm0KEQqgSRteOSBawq4FXcZLBK8=,iv:CToBAR7LCzZFLWBYxlwKxRHjFeJCO11DHqZAgWKY6ZM=,tag:wyLFfrRGBD4a++uyzmM8GA==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:0yXmoWEHScgk8ZtZs4rGXp913+yidFOyOaoK12g/RBVN5AYm6hbyKDOwiPrTLoga5iQxRGaVygBHVf+owWSOiw==,iv:ybic1Pe0pmaiDlYzZL3wcWqmgY0rHIGv6aZeo2AfC78=,tag:ojoFGPLAE98Dcn7O4Dk/IQ==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:i9SUL76xuhRFw6X/tjngFBlY,iv:IxYdTRjp79l8pVX2VnffXoo1pVp/Stbp4+5Ot8jB7Q4=,tag:lHYUN+9/y0+AjS6unrxxtA==,type:str]
    tag-source:
    -   implementer: Git
        config:
            git-password: ENC[AES256_GCM,data:OHWf1s9PupYgLuoe,iv:RaTfe/DyTH9SqQUFoZ9O5Hdl0HGQ3YT8LKuTyRyC3wM=,tag:uy+NHJ9JICN3mXhpWqJNFA==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:naVtkfyECDEb865C6dblluhV,iv:IUsyBh9kD1ME3UM2r8xKarHnP9ml9hcG/+rM0STxTFA=,tag:AJOi17GdgOldQ1AmTDp4ig==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            argocd-password: ENC[AES256_GCM,data:ybFFcQJN,iv:C0uuG7Qcq0APBWQ1h9vc+bG3uIyCpKDarv+VIaTVNXM=,tag:ccbZw5ALCEYT59CFn6bfcw==,type:str]
            git-password: ENC[AES256_GCM,data:vzyxspv3XZMlt5nG,iv:6lh2/+sT1wi/g2k0mCFAF0AmNH/YPMkIoxlBgGrAfQw=,tag:i+hXx3QudhlTve4sSvzYPw==,type:str]
    report:
    -   implementer: ResultArtifactsArchive
        config:
            results-archive-destination-password: ENC[AES256_GCM,data:36c2LECMISLdAfBknUWf6Rfo,iv:/YLeh8aO7z6hEGaFTHgyyFpSsFbr9aB23botWwe9qrs=,tag:OhsN0OqlbJrJnqmTjAVhSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-06-14T20:05:30Z'
    mac: ENC[AES256_GCM,data:6j8jsIUKUyIsNc31ZRkSQq+HEAbPntNk3wQOXo1UP68zzoO2UH5szzjA+yx+2JZt7MgzGg8PGLUMehPm/s3bqH9AyVJYVTj+iVgJ8Sx61gEnViUxRAe6bci4eeBSDtNzu4+qnS7x2ZT/Q5xm5ejwjF/H0zLkc2rUfyIJSuUreyM=,iv:WLg5FI6B6dfZqhAivkBN2g2BC2dyC1FTd7lZVEnlEHE=,tag:q1H5IcEhodG33y3hGydEKQ==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf/YGzNNjEL5aSGZSuwaGGXa389v9Ef0nm1i2z3mR34SnwW
            1XWaC/jDnDvY7Qiqvb2xKS2wy2ShZQMqVQt+IjTP2z+Hz/gW8WcuMLdzF0aExzOp
            grPnCaY7m/AoT14aBI31TfOhLvpOuMhX6qD2aoSJM0TQdXPZKphtmL4ccVT5iIlF
            flErgaIxHtUt5RlUJ+LvfUaTZAqDSKna4PiSBNcPEu0/lc264G6gJCssj3ZIh0O0
            s/7A+0/Uf7+AqpRiLIHXP8y3XeqOCQfhiul7wHOKOKpNwRHolJdwShf8AmVcSRmz
            AbEDoc3vrQgPBE3mQGzhXjIfI2Yq6NbXM+MIiQkfM9JeAbOxRqgQnwL6FmFBny/n
            RzPHUbHxCSs0JDzS32DxuUflMy0OihxMkvR2+5cOil2qBveQwdGlNtpK9iVpJ47N
            AvYUUMNazmEYwDnoZxctQcWQRFOMVLckmYNlNiSYBw==
            =zzUS
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ//WGt/OWyC5Xh+EVxBSl/96QVCcLMMAeu5/ZOWqa0laojM
            DPrmcD1dMtp86uvUjhGyl9UlpKq0u7WzBJlXvxdbPTZ6x4AIoOb9XQQcjnhbqyU2
            TEgB0lljJfjZCep7ZY8q8aimWEYyfTuJAAQEtgyCMwEDU065mihWcGtjwVWJaFlf
            WhNvlmDlUxuZv9jKPWmjiMBIV+rUXm+9vNDrYipLCJqpCW2bJlj7bGs+ihhgiAmv
            CBn6vgGWO1TnT+vV6rElHooHA8aZHAXlYR9zhmlkx1R72ZxeW5yUGbr6dFxRnM3m
            K8XPK+/6kYda3WpiF6TriLiuUetE6BDpCAG6DkZTBLDJro0VRxCmP9HIeEnG75f3
            nd/b8U4tOKNAVsBlmlNd+oMdc8FbhzdgFQ9WUMNQX6sfNNaactJ6q8lic2FkYG0a
            xytIbaXIO82FYw0coprl3qy8gGxt1m5uZTXDM9w+xF20g2Mcs1lZvrQq+OlYM8jD
            FtQL0okNSOC4oUQ23DPeeuoF32ygIshHV29gB8bkrhF+ZdlpUJ+4EoGkZl/80x8B
            exBBte5XZ4lYAD8H+iHmmeWCqz1lUlqyJsyPGRQphxNlkgReotfNOCYz+UftmxzF
            pjoc3WHwhMixizScTcZl5ZnRd9fAV+UZ/DI8iKfQ7j6uDF+V9P5VtDd8V5Hn7FPS
            XgE5X+3LoyxiZUPkuAVIWrC5a9cMdvP5dSZ1VrY1H6d1UMKC4yauBel1J4jq2niK
            NeFP/71ZxJljM4R000DalSaDoJZ+gegVTLkv3O0N3OVb3Gks9QImqrdLxrcubD0=
            =t54E
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf+KJDZWuNmQ9QBJwP4EGcbT10i3kFcAmjcjRxpV2MrXoXL
            iaDgBEbJafA3lUApJB1Uo6O3nReTH+fA/TDt8Y5qe04zZX3prDmXlHieAWyfaNJz
            +F28Rq8BPqXW2CG/aM0Dfkh2MH7ffOqljATnmrmDD080tuoJj1EGM4hH8uhYFJtL
            VNSsyAUQtXo+F/3cg4IVBcpjfAEEZwlYUvQmgAOiEbIQHoQDEUGprHefvRvD3toh
            D8ZgVzgIBFtjEf7tExGr3jWR4yOhyJjl0tacPpd4NZeyIXTOT3aIqlmRBH22RXYh
            SK3LsoVKqsAnKobgtDmu9VgITyZbKz585KwhPH1w3tJeARP6v7C7mX64QX7SIx60
            azXySdKI0MP3B7T1MwoV5BULmupUbASe4sXAOMGifb4OEgrCJ61k4ILKgN7DlW/I
            T62N9PH0+nTmYLREgNIUwfjXQcilI3/ppwNx1Ogm7w==
            =KpY9
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQAQ/+LtdJGJdXMvZesb64+b6wi/hQhPZbI83jEYu66B+tzhV7
            hr+EzwpTQHLpI7qYidCoWy4Q/d0FMVA21d9xhxRSvb8JaTKlVTs7zhqQr4FuTWXX
            +bSD0IKzLe3rd76aSizdsQmfXzx0nfjfRVXkVdDU1RW5TLu5dOySXq8dr+h2jvuz
            MYwROdBKdYl/tImmUchH5aHHBV29De3Naucjvn2KfrE/h9SRaCoFpcO4hU+u8Rar
            2vbaUr3Lv24MQ6wgPXKXKtRcch5zwFzC9ghHMwJysZvisheKLx2WvuqJoiAJsOcb
            gsfzTfReLQpNzPh8GFZEC9haUMPsHpZEz8Zpy/dkHo4eX8eGg7ntYr/HMu7r9pgA
            eFsjithFYnyC/Xn6L3e5+iTDizD0faRbk7B+xmExohEDV6zQUekAldsDz/GQL0C/
            Ek/2XIuNhm5x5B5PDtX6rHvFBbD5qxBWbsreDh06prH82A7O8c4aDjFSwUPT4m7O
            KtkuIeYYBfZlHp87wAOjROGOqRLSftO87E/2EubPmXyPOt9r3ojlyE2bYeLQcnwA
            G7g6wfprx/xQ4P2HNQXpbeeuh3+2TenLrU7MS5t8QNOCecZkKo8JiTB5gig8roR6
            yGJrnLVFnpMM+YISOt1lLbOvphz+Ywat446+xkRSRHgkOVJlRE11lzwrlB37EmzS
            XgGf3QpAQNQhz1CnH2OcQWH+7QW4eEyOKIooAyM3MC2FN/mv+SMF0yUD2uzfCylj
            1ShLMBev3LudXnVO1VIYgMhq1VQdPjrQaNLVkbSCskbBg5Qmx1d3Murs7kc/BZU=
            =TPYf
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmARAAhAbTJrM9Tza+qYODOWL7rq9LUIxR5+GTX88Ge4UAJPMI
            XzWJxHa6tHg1t/EwaI8KY3S7U2KXMuV8UGGGSrkqEu0fawlHOdF+KCkgwNK5WqD/
            quSKHSFBUhXrSlb29kFgFn6wdlrZivIbTU3DzpRHOs7UIne/U5RQw2k7IPVCCJXI
            l8BI9mVAqA3Np0Rlb7typQbohf1F9+7h/LTmoPc8OXjOBU9KLAd3mX7qbeGqh9mM
            vlhW8+IWPlPGwZe7W49QaLxKOwE8c6r7foOgw3uR7R9MLzw0sZGTUct6iCpa2qce
            1UpiftjAqi8Jk9hTmuGF0utZbR46kkMQsSoaDKuEwKQjMkOljC5vUDdcV8E6ofKh
            LKeV4IH705Bvrw2pIJuxlT4NRPqUQHrVWj46UDFM4uZWgDBRDxFI/97B/X6OoGFO
            iTAUahatvkbRw6umIRq2eTqZMEBuuHOhE4DI0LH0KYuPe1QvU5W1SbTuXDOsB5VI
            3YMlldg9en4Uv6BhgVY32qwZj30jpbcMx8rjTl4VAM8/UjYaA1iaoKLQMKJxBEEv
            1LIr1D5klMVSfS6zbxK9QtKVZHJs9+tHOvWIazIAKc4njEvyE1YNKGZdFvtbHeaH
            zDavjG/gbbhGT4u4EW9dweq6Vt4ZfA2FpwzDVU9oeKkuuMPvSdIdUw1U0iT4/BjS
            XgFhtuFFl96M/222M+bzA1XYsKMaAt/EK/GZ4giUCBvkAzIynETvxo5JW/R8QSbd
            RTrTdYGVrrkNWAy0RsWRKHF79DtU3uW+ZxSscfJ1KgHLJanYQ0wtdkEd1yO5dRA=
            =1MnF
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHARAAka5JxT/XKvP3zQcqMLepeNSjXRmtYCtd3+/xJIt8fFuE
            da/t98yDiMpV2V2hUvHUwyxRxlhuCll5C6yEBkhqRQE0OiD8X/+GyQ7UePTfSiCl
            ldFkot6kXy2q2d0yeH9MmFASC30IGVyxhRUUjEqY+ML6m+ZCNAx7Vo28qWc7ZmZ+
            qNGs3mpItiBb/ak0iQYAVBhPauW6HB07FF/ULBd/ch1bP8fCn+H27uy7VISxrrff
            8dlHHbHjixhjsC2xSvGDd0FMCN2xi3dP8LDDzuJN9Hdl1VvODlW7kiBYowfIT3TS
            6kXbBEd/h+6HvH2ZOhsc/G3j4jRmAJ8eg/MI8IdijooMGkObjRkE0/mAXJ0lLwhg
            mswiSEwEFXtE1Pvkgtm1Qc4Gl855CrlWGThN0XBiHXADL8zU46YjqpuielLl7mnJ
            BHtUCVnhkpE5+mdMBBUFpScPWagGvBmqe5LulS1HAw6yYHofSeB7HZRmMlwF30yU
            bHK1lAkULtXjWXzRJ24ij5pkQBZ9J87MWHsGgN7Cfwjp07KVSA89htvpBzqh+5VN
            VzEUh9UUe6ENHJcb+bIamcBOxtQ0q192t3lwFQB+V1kSEUDl8gsFuxRM9Dmgn5Ic
            V9WJgnbWG9lN/7p5452ozHrPxL3hIpJOvI4j0LDwWAEZf37tyLfQDD62PCmGCUXS
            XgFHNbnfVSTpmQOWeBmAA1bWtl5e8k5H4Fb1+8/WyeMIT4UFRZQrvk+nywT8KH6S
            gEkvOqbMBlChIpIVdOkfNKv98tOd9+Kuacd4ZoZDNi53KSBHWRr/IZ13EQFgAjY=
            =2zTE
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQv/SZ47kpf82rVDs2SNltPyyYXSFE/x7OZ5tgDVR5Ie7FdA
            w7MatIHNC33SFmCARs4l5L3w0FGL5oM4eDH0iL7AFclBEclhRSx724T8Evs11APp
            KSgqDTo7/TzOZKwDr8xfdZyDZ4adNcOeVLfeUS5ZUV/sSuCXhsh2fNEQUqfAyoib
            q/hekaWfjHghKeVgsAVTlOHGrewl+DEOY5YYDsSsWjq+zM0kxGXBOhf5ErUISePV
            lXw1v8hak4Tv4QsVylrMvYcsCA3/9DZ31FmzyvPXij+XemOUIVD1lBvKijkloclp
            rKZBqMjHuzoZzWgcYPxQ365VISjWWjA4hxdEGd/mDPBuXp15KQLYA/PO0RMzKTHH
            eqou9rRMpmhe3K9zhf3nGjceU+/U7UqzwLq4T4lm+YF4J0Saip/6hlyZFwhSEDwg
            xoCZD6lPSDWbsSqHZsIx62YId1NUssuG48ZYIR0LyewCzrBtcODZkO1gw3MwaOBF
            Rz++CWMsZTPXSIiCFnLg0l4BlSVU1cVaX9pGMYhfBFpiPgRGX6bjdyplqevjzF8L
            FxguxwQUFPoUny72bvjFasyBEv1SGOghIBls1iTHAJwhOIpF68/b5HAzkzgPcXVM
            618zJYNQ9Xv70N4i4Yik
            =Parb
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAgTRNlIHPmhEf60aAyK4g4sWIvbqlOSxct0PjfOhii8q/
            JVDsBkm/A3rYlEHIK980x1xB9wEC+Kr6c8PzXAxacsHJGUbJZdD+s2Ph7DS5F1xL
            7reU4m2HB4ImYmWbXCFdgVn8kJmQtnlzbRaAGLQbSWOPKl83N62yoPFadUwmrxw8
            D9e5HEwLXj+QiFz3aggw5FbGMp2hTXR2E07u5L/lIMmcftSj1YEtcDlLp+JrXbvi
            eZGUJOep0iTOxxtVGRFJyqS0jRkAmc/sH0NKFIa1w3SSfgkBWwmA8fBeSl4OoWa8
            om5zUhJJR7no8HTpHQQgQI0F3W2CDK22U/u9xIqkg9JeAbDVcr2wxOnNo5mrderm
            +wha3flCWNoUasv0uqojTXiSyTY+0JHumxPNuidtAp34yXIdtuyHp/wCjEp4DWG6
            bGR9fZ+lDZPBFp6uJ/OSt/E93eZiOsBbToV6py3IUQ==
            =cYo/
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQv/UIsswI/T+D0KZDKSbnvAkcjDFe/NrSLW16RKwKL36zrp
            Mf/IJeIXJK7r5ZwnB9u3BmI+OaUD7biFdABxPo6pYqMRpQRUsViMGPBzYB+s+vcB
            sMbesHuyKzVjU0/6iULA76YFi8Hl2c8NtYS2m2nsEMQbUhDlCQsIhiiHy3GYMC+Q
            iDIesp//d8hm2VGNCDLeF2XEsURsGIJJEk+s4C0tv4kHotum6iVqqVK+18oputKC
            TfNf3W3KMt03JIvdmhYxjH5QWnKSrgd8EzasPT5KmNrbM54evK2iTcVvm3timTBh
            v0jFQAWtR6ggHGTAI/XKuYidIoSa5BYgiLOt+zSAzng6xD3xpa96smGmopK7tRiA
            tIY7TZtmwhZKgNuc3LzPM9tNWPdGqd3G2uAk8hhYivHOlI4QgwZ7jKtv4qpuXmME
            Z28zgU7VznqZXue7xrIRlAs99psYkbhL2oub6/WpG/3SB1fcTYNzTzjoBs6ZnUio
            YZM6Oe+VbHQvu3D046Xb0l4B0OPLMCrswa7PvqRrFO8o7yApOubEQzl5H9hVOMir
            gmCM+8reQMASjI2JtqdJFqSNWoIXqbYjD+yhOF02nOTPxAZ9Yxb3JZgsajXKXEhv
            2SG8sSY7844/1SApttec
            =m8kp
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    -   created_at: '2020-09-30T21:54:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0sgQJTuz3CvAQf/VZUA4Hq1nNT/2QzgfxCGN7qaZfrib6Vkr69au56R01bv
            9KXu2FwrVnAXy5ZT477+iYjcjGPxHfd0Qu5+nzEX9GW+pCCdVS6IP0+sy1O4ciiL
            B1CstyAK40Xus14TxGz365zklr60MRT8cGAm22XN+9bDa6L9U60AABdq5hd8FEam
            oI5mEFHs3LVTa19NqDQv3I6uI56xQ3bHfS8L9yWdhjTvBh6ruEFNEXyR/7XY7ef6
            pQamT47QxKgCkhxhlIpCfAeCiZwdBwusX2gX8B2fzMzb4S6hRmv6me2J9KqoihPg
            ehqUHlWPgN0syn2ykBZ2X5QN2AEmRQQ3nUXGGKRT3tJeAR9rh1dH+6UErtzuhwG4
            13w1UlqtfId8x5xTK6MJJ064+EoHa9dyZpLdCkoyDVWvJVVU0lArfhntSmX7ESgf
            EdtY3k8c636J0Th78iChtqPH3F6fepWkHJ+3xNjGkg==
            =w685
            -----END PGP MESSAGE-----
        fp: 84D2732F14E43B7540DF0074679ADA89F304FFB1
    -   created_at: '2020-11-16T15:30:53Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5DboIX0e/riAQv/X51D+poYJuZAsCgnQXBB7ZeQYU7ugMmIaZWNmGuY23Dq
            ZudVQZe0OXBzPhrXZmmEwlwhUT1URO9k2eVTHKfUbAnw4WR3iv8KAoKR+VPWUWO8
            Y/wnqYtvAXMmmxF+Rdmphbv4PJ4hFNBPY/DjIEtL5AdGNSc/xKZeH25kCnSDDYvS
            E7ee0vXdz6wUDa1pvWdZ2xypFbpr+7NSFnCKjWY/lHNM6P3DR9f5ov0avhPsKbE0
            UjwZ+QmvpARQOLYyr34K+VY+xTDYPAGZvQJhW8B7zx2KCsqk5DAX7hCTnucuBnj1
            EaVR4PB+VnbG6P6jeR/mc9T+pNEuUFvDUfNSWOHXQvvXLzucaO/uTuhTrfAoSyN9
            4ZnD5SSphJVBAiscug3cu3RggRwFJyNUNvBRoq3DljpytzkE5pUHVKdULb0grIE/
            YlxdN0apALy0FwTOVqSjeV8oDykJwL+AfMLDXJLLexP/0czDwjQQVYlDx/SWBtKh
            wBfXgO2KD4SzOE+kfKlG0l4BeJsY6x3mZHHTDAe1g06Lb/1XWBgMcY5VJREqsyrc
            xgtBMhteWLIQBwc52RK2aRiMJ9/zoRW5dsikXwViP3qfowcmdE+2atvDdTkj+hyI
            PRR/PMOnQJBvz5rRQVim
            =kCTV
            -----END PGP MESSAGE-----
        fp: 54AE25FAAAF84ACAB4F1BF907696644F2069EBDA
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
