// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@allow-loaded-implementers',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/adamgoossens/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowEverything(
    stepRunnerConfigDir: 'cicd/ploigos-software-factory-operator/ploigos-step-runner-config/',

    workflowWorkersImagePullPolicy: 'Always',

    pgpKeysSecretName: 'ploigos-gpg-key',
    workflowServiceAccountName: 'jenkins',

    workflowWorkerImageDefault: 'quay.io/ploigos/ploigos-base:v0.20.0',
    workflowWorkerImageAgent: 'quay.io/ploigos/ploigos-ci-agent-jenkins:v0.20.0',
    workflowWorkerImageUnitTest: 'quay.io/ploigos/ploigos-tool-maven:v0.20.0',
    workflowWorkerImagePackage: 'quay.io/ploigos/ploigos-tool-maven:v0.20.0',
    workflowWorkerImageStaticCodeAnalysis: 'quay.io/ploigos/ploigos-tool-sonar:v0.20.0',
    workflowWorkerImagePushArtifacts: 'quay.io/ploigos/ploigos-tool-maven:v0.20.0',
    workflowWorkerImageContainerOperations: 'quay.io/ploigos/ploigos-tool-containers:v0.20.0',
    //workflowWorkerImageContainerImageStaticComplianceScan: 'quay.io/ploigos/ploigos-tool-openscap:v0.20.0',
    //workflowWorkerImageContainerImageStaticVulnerabilityScan: 'quay.io/ploigos/ploigos-tool-openscap:v0.20.0',
    workflowWorkerImageContainerImageStaticComplianceScan: 'quay.io/agoossen/ploigos-tool-stackrox:latest',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'quay.io/agoossen/ploigos-tool-stackrox:latest',

    workflowWorkerImageDeploy: 'quay.io/ploigos/ploigos-tool-argocd:v0.20.0',
    workflowWorkerImageValidateEnvironmentConfiguration: 'quay.io/ploigos/ploigos-tool-config-lint:v0.20.0',
    workflowWorkerImageUAT: 'quay.io/ploigos/ploigos-tool-maven:v0.20.0',
    workflowWorkerImageAutomatedGovernance: 'quay.io/ploigos/ploigos-tool-autogov:v0.20.0',

    separatePlatformConfig: true,
    customStepImplementersSourceUrl: 'https://github.com/adamgoossens/psr-step-implementers.git',
)
